name: ohioriverhouse
favicon: null
layout_spectrum: 0.060041069984436035
typography_spectrum: 0.15770892519503832
title: The Ohio River House
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.661254930542782
  lightness: 0.15444925311021507
  saturation: 0.16059487452730536
  rhythmicContrast: 0.38528792606666684
purpose: []
